version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - run: |
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -y
            sudo apt-get install -y --force-yes yarn
            yarn config set workspaces-experimental true
      - run: yarn install
      - run: yarn test
